
services:
  flask-app:
    image: harshporwal01/flask-app:latest

    container_name: flask-container-compose

    ports:
      - "5051:5050"

    volumes:
      - flask-data:/app/data

volumes:
  flask-data:

